module ViewFormat exposing
    ( ViewFormat(..)
    , viewFormat
    )

{-|

    This module is generated by the Rust program in src/main.rs.
    Do not edit it directly.

-}


type ViewFormat
    = Web
    | Pdf
    | ThankYou { recipient : String, message : String }


viewFormat : ViewFormat
viewFormat =
    Pdf
